version: '3.4'

networks:
  docker-compose:
    ipam:
      config:
      - subnet: 172.21.2.0/24

services:
  api:
    container_name: api
    networks:
      docker-compose:
        ipv4_address: 172.21.2.2
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/api
    entrypoint: /bin/sh -c 'npm install && npm start; tail -f /ws/docker-compose.yml'
    environment:
    - HOST=0.0.0.0
    - PORT=4000
    ports:
    - 4000:4000
    healthcheck:
      test: >-
        /bin/bash -c
        "echo -e \"GET / HTTP/1.1\n\n\" > /dev/tcp/localhost/4000 || exit 1"
      interval: 10s
      timeout: 1m30s
      retries: 5

  frontend:
    container_name: frontend
    networks:
      docker-compose:
        ipv4_address: 172.21.2.3
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/frontend
    environment:
    - PORT=4200
    - HOST=0.0.0.0
    - VUE_APP_API=http://172.21.2.2:4000
    ports:
    - 4200:4200
    - 4300:4300
    entrypoint: /bin/sh -c 'npm install && yarn serve; tail -f /ws/docker-compose.yml'

  acceptance:
    container_name: acceptance
    networks:
      docker-compose:
        ipv4_address: 172.21.2.4
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/acceptance
    entrypoint: /bin/sh -c 'npm install && /ws/acceptance.entrypoint.sh && npm test; tail -f /ws/docker-compose.yml'
    environment:
    - APP_URL=http://172.21.2.3:4200
    depends_on:
    - api
    - frontend
    - hub

  hub:
    container_name: hub
    image: selenium/hub:2.53.1-beryllium
    environment:
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
     - 4444:4444
    networks:
      docker-compose:
        ipv4_address: 172.21.2.5
    healthcheck:
      test: >-
        /bin/bash -c
        "echo -e \"GET / HTTP/1.1\n\n\" > /dev/tcp/localhost/4444 || exit 1"
      interval: 10s
      timeout: 1m30s
      retries: 5

  firefox:
    container_name: firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
    - 9000
    depends_on:
    - frontend
    networks:
      docker-compose:
        ipv4_address: 172.21.2.6
    healthcheck:
      test: >-
        /bin/bash -c
        "echo -e \"GET / HTTP/1.1\n\n\" > /dev/tcp/localhost/5555 || exit 1"
      interval: 10s
      timeout: 1m30s
      retries: 5

  chrome:
    container_name: chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
    - 9000
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - TZ=BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    depends_on:
    - frontend
    networks:
      docker-compose:
        ipv4_address: 172.21.2.7
    healthcheck:
      test: >-
        /bin/bash -c
        "echo -e \"GET / HTTP/1.1\n\n\" > /dev/tcp/localhost/5555 || exit 1"
      interval: 10s
      timeout: 1m30s
      retries: 5
